### ISSUE TITLE
can't find this plugin on Manjaro Linux

### ISSUE THREAD

**Issue by Ryder17z** [PintaProject/WebPAddin#6]
not listed in pacman even though snap, aur, flatpak is all enabled

**Comment by cameronwhite** [comment]
Could you be more clear about the issue? Are you unable to install the `libwebp` library, this add-in, or Pinta itself?

**Comment by Ryder17z** [comment]
this add-in.

**Comment by cameronwhite** [comment]
If you go to the Addin Manager -> Gallery -> Repository -> Manage Repositories, do you have the platform-specific Linux one? It looks like the webp add-in was only published for Linux (https://www.pinta-project.com/Pinta-Community-Addins/repository/Linux/ vs https://www.pinta-project.com/Pinta-Community-Addins/repository/All/)

**Comment by Ryder17z** [comment]
They're both enabled. However, the Gallery is empty, clicking refresh just returns an error:

> Exception occurred: Could not load type of field 'System.Net.HttpWebRequest:tlsProvider' (49) due to: Could not load file or assembly 'Mono.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies.
> 
> System.TypeLoadException: Could not load type of field 'System.Net.HttpWebRequest:tlsProvider' (49) due to: Could not load file or assembly 'Mono.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies.
>   at Mono.Addins.Setup.AddinStore.DownloadObject (Mono.Addins.IProgressMonitor monitor, System.String url, System.Type type) [0x00002] in <66926db7724b4a15977d262512f6cfe2>:0 
>   at Mono.Addins.Setup.RepositoryRegistry.UpdateRepository (Mono.Addins.IProgressMonitor monitor, System.Uri baseUri, Mono.Addins.Setup.RepositoryRecord rr) [0x0003a] in <66926db7724b4a15977d262512f6cfe2>:0 


It looks like a problem with Pinta itself, so i'll see if there's already a similar bug report already.

**Comment by cameronwhite** [comment]
Thanks, I'll close this since https://bugs.launchpad.net/pinta/+bug/1919281 is tracking the issue
